/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

/**
 *
 * @author jorge
 */
public class MenuTerapeuta extends javax.swing.JFrame {

    /**
     * Creates new form MenuTerapeuta
     */
    public MenuTerapeuta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        Pacientes = new javax.swing.JButton();
        Perfil = new javax.swing.JButton();
        Agenda = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(714, 540));
        getContentPane().setLayout(null);

        jPanelFundo.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanelFundo.setLayout(null);

        Pacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/Pacientes.jpg"))); // NOI18N
        Pacientes.setText("PERFIL");
        jPanelFundo.add(Pacientes);
        Pacientes.setBounds(280, 150, 160, 60);

        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/Perfil.jpg"))); // NOI18N
        Perfil.setText("Pacientes");
        jPanelFundo.add(Perfil);
        Perfil.setBounds(280, 260, 160, 60);

        Agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/Agenda.jpg"))); // NOI18N
        Agenda.setText("Agenda");
        jPanelFundo.add(Agenda);
        Agenda.setBounds(280, 370, 160, 60);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos/fundo2.jpg"))); // NOI18N
        jLabelFundo.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabelFundo.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanelFundo.add(jLabelFundo);
        jLabelFundo.setBounds(-1, -3, 700, 500);

        getContentPane().add(jPanelFundo);
        jPanelFundo.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTerapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTerapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTerapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTerapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTerapeuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agenda;
    private javax.swing.JButton Pacientes;
    private javax.swing.JButton Perfil;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JPanel jPanelFundo;
    // End of variables declaration//GEN-END:variables
}
