/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.terapeuta;

/**
 *
 * @author jorge
 */
public class PerfilProfissionalSaude extends javax.swing.JFrame {

    /**
     * Creates new form PerfilProfissionalSaude
     */
    public PerfilProfissionalSaude() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundoPerfil = new javax.swing.JPanel();
        jPanelPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jLabelApelido = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDataNascimento = new javax.swing.JLabel();
        jLabelMorada = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelNTel = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jLabelNacionalidade = new javax.swing.JLabel();
        jLabelSexo3 = new javax.swing.JLabel();
        jLabelUtente = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelFundoPerfil.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanelFundoPerfil.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanelFundoPerfil.setLayout(null);

        jPanelPerfil.setMaximumSize(new java.awt.Dimension(858, 500));
        jPanelPerfil.setMinimumSize(new java.awt.Dimension(858, 500));
        jPanelPerfil.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Perfil");
        jPanelPerfil.add(jLabel2);
        jLabel2.setBounds(20, -10, 130, 60);
        jPanelPerfil.add(jLabelFoto);
        jLabelFoto.setBounds(50, 50, 0, 0);

        jLabelApelido.setText("Apelido:");
        jPanelPerfil.add(jLabelApelido);
        jLabelApelido.setBounds(450, 30, 60, 20);

        jLabelNome.setText("Nome:");
        jPanelPerfil.add(jLabelNome);
        jLabelNome.setBounds(250, 30, 60, 20);

        jLabelDataNascimento.setText("Data de Nascimento:");
        jPanelPerfil.add(jLabelDataNascimento);
        jLabelDataNascimento.setBounds(180, 60, 110, 14);

        jLabelMorada.setText("Morada:");
        jPanelPerfil.add(jLabelMorada);
        jLabelMorada.setBounds(240, 90, 40, 14);

        jLabelSexo.setText("  E-mail:");
        jPanelPerfil.add(jLabelSexo);
        jLabelSexo.setBounds(450, 120, 40, 14);

        jLabelNTel.setText(" Nº Tel.:");
        jPanelPerfil.add(jLabelNTel);
        jLabelNTel.setBounds(240, 120, 40, 14);

        jLabelCC.setText(" Nº C.C:");
        jPanelPerfil.add(jLabelCC);
        jLabelCC.setBounds(240, 150, 40, 14);

        jLabelNIF.setText("   NIF:");
        jPanelPerfil.add(jLabelNIF);
        jLabelNIF.setBounds(250, 180, 40, 14);

        jLabelNacionalidade.setText("Nacionalidade:");
        jPanelPerfil.add(jLabelNacionalidade);
        jLabelNacionalidade.setBounds(210, 210, 80, 14);

        jLabelSexo3.setText("Sexo:");
        jPanelPerfil.add(jLabelSexo3);
        jLabelSexo3.setBounds(460, 60, 28, 14);

        jLabelUtente.setText("  Nº Utente:");
        jPanelPerfil.add(jLabelUtente);
        jLabelUtente.setBounds(430, 150, 60, 14);

        jLabelEstadoCivil.setText("Estado Civil:");
        jPanelPerfil.add(jLabelEstadoCivil);
        jLabelEstadoCivil.setBounds(430, 180, 60, 14);

        jButtonEditar.setText("Editar Perfil");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanelPerfil.add(jButtonEditar);
        jButtonEditar.setBounds(340, 290, 130, 40);

        jButtonVoltar.setText("Voltar");
        jPanelPerfil.add(jButtonVoltar);
        jButtonVoltar.setBounds(490, 290, 130, 40);

        jLabel4.setText("     Instituição:");
        jPanelPerfil.add(jLabel4);
        jLabel4.setBounds(420, 210, 70, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos/fundo_branco.jpg"))); // NOI18N
        jPanelPerfil.add(jLabel3);
        jLabel3.setBounds(0, 0, 660, 350);

        jPanelFundoPerfil.add(jPanelPerfil);
        jPanelPerfil.setBounds(20, 110, 650, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos/fundo2.jpg"))); // NOI18N
        jPanelFundoPerfil.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 500);

        getContentPane().add(jPanelFundoPerfil);
        jPanelFundoPerfil.setBounds(0, 0, 750, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilProfissionalSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilProfissionalSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilProfissionalSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilProfissionalSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilProfissionalSaude().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelApelido;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelMorada;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelNTel;
    private javax.swing.JLabel jLabelNacionalidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelSexo3;
    private javax.swing.JLabel jLabelUtente;
    private javax.swing.JPanel jPanelFundoPerfil;
    private javax.swing.JPanel jPanelPerfil;
    // End of variables declaration//GEN-END:variables
}
