/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend.terapeuta;

/**
 *
 * @author Quina
 */
public class Perfil_Paciente extends javax.swing.JFrame {

    /**
     * Creates new form Perfil_Paciente
     */
    public Perfil_Paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundoPerfil = new javax.swing.JPanel();
        jPanelPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jLabelApelido = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDataNascimento = new javax.swing.JLabel();
        jLabelMorada = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelNTel = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jLabelNacionalidade = new javax.swing.JLabel();
        jLabelGrupoSang = new javax.swing.JLabel();
        jLabelSexo3 = new javax.swing.JLabel();
        jLabelUtente = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jLabelPatologia = new javax.swing.JLabel();
        jLabelDescri = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonPrescrever = new javax.swing.JButton();
        jButtonRelatório = new javax.swing.JButton();
        jLabelFundoPerfil = new javax.swing.JLabel();
        jLabelFundoPag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelFundoPerfil.setLayout(null);

        jPanelPerfil.setMaximumSize(new java.awt.Dimension(858, 500));
        jPanelPerfil.setMinimumSize(new java.awt.Dimension(858, 500));
        jPanelPerfil.setPreferredSize(new java.awt.Dimension(858, 500));
        jPanelPerfil.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Perfil");
        jPanelPerfil.add(jLabel2);
        jLabel2.setBounds(20, -10, 130, 60);

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fotos/perfil.PNG"))); // NOI18N
        jPanelPerfil.add(jLabelFoto);
        jLabelFoto.setBounds(50, 50, 81, 80);

        jLabelApelido.setText("Apelido:");
        jPanelPerfil.add(jLabelApelido);
        jLabelApelido.setBounds(430, 20, 60, 20);

        jLabelNome.setText("Nome:");
        jPanelPerfil.add(jLabelNome);
        jLabelNome.setBounds(260, 20, 60, 20);

        jLabelDataNascimento.setText("Data de Nascimento:");
        jPanelPerfil.add(jLabelDataNascimento);
        jLabelDataNascimento.setBounds(190, 50, 110, 14);

        jLabelMorada.setText("Morada:");
        jPanelPerfil.add(jLabelMorada);
        jLabelMorada.setBounds(250, 80, 40, 14);

        jLabelSexo.setText("  E-mail:");
        jPanelPerfil.add(jLabelSexo);
        jLabelSexo.setBounds(430, 110, 40, 14);

        jLabelNTel.setText(" Nº Tel.:");
        jPanelPerfil.add(jLabelNTel);
        jLabelNTel.setBounds(250, 110, 40, 14);

        jLabelCC.setText(" Nº C.C:");
        jPanelPerfil.add(jLabelCC);
        jLabelCC.setBounds(250, 140, 40, 14);

        jLabelNIF.setText("   NIF:");
        jPanelPerfil.add(jLabelNIF);
        jLabelNIF.setBounds(260, 170, 40, 14);

        jLabelNacionalidade.setText("Nacionalidade:");
        jPanelPerfil.add(jLabelNacionalidade);
        jLabelNacionalidade.setBounds(220, 200, 80, 14);

        jLabelGrupoSang.setText("     Grupo Sanguíneo:");
        jPanelPerfil.add(jLabelGrupoSang);
        jLabelGrupoSang.setBounds(190, 230, 110, 14);

        jLabelSexo3.setText("Sexo:");
        jPanelPerfil.add(jLabelSexo3);
        jLabelSexo3.setBounds(440, 50, 28, 14);

        jLabelUtente.setText("  Nº Utente:");
        jPanelPerfil.add(jLabelUtente);
        jLabelUtente.setBounds(410, 140, 60, 14);

        jLabelEstadoCivil.setText("Estado Civil:");
        jPanelPerfil.add(jLabelEstadoCivil);
        jLabelEstadoCivil.setBounds(410, 170, 60, 14);

        jLabelPatologia.setText("Patologia:");
        jPanelPerfil.add(jLabelPatologia);
        jLabelPatologia.setBounds(420, 200, 48, 14);

        jLabelDescri.setText("       Descrição:");
        jPanelPerfil.add(jLabelDescri);
        jLabelDescri.setBounds(220, 260, 82, 14);

        jButtonEliminar.setText("Eliminar Paciente");
        jPanelPerfil.add(jButtonEliminar);
        jButtonEliminar.setBounds(340, 320, 130, 40);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanelPerfil.add(jButtonVoltar);
        jButtonVoltar.setBounds(490, 320, 130, 40);

        jButtonPrescrever.setText("Prescrever Sessão");
        jButtonPrescrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrescreverActionPerformed(evt);
            }
        });
        jPanelPerfil.add(jButtonPrescrever);
        jButtonPrescrever.setBounds(190, 320, 130, 40);

        jButtonRelatório.setText("Gerar Relatório");
        jButtonRelatório.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatórioActionPerformed(evt);
            }
        });
        jPanelPerfil.add(jButtonRelatório);
        jButtonRelatório.setBounds(40, 320, 130, 40);

        jLabelFundoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos/fundo_branco.jpg"))); // NOI18N
        jPanelPerfil.add(jLabelFundoPerfil);
        jLabelFundoPerfil.setBounds(0, 0, 660, 371);

        jPanelFundoPerfil.add(jPanelPerfil);
        jPanelPerfil.setBounds(20, 110, 650, 370);

        jLabelFundoPag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos/fundo2.jpg"))); // NOI18N
        jPanelFundoPerfil.add(jLabelFundoPag);
        jLabelFundoPag.setBounds(0, 0, 700, 500);

        getContentPane().add(jPanelFundoPerfil);
        jPanelFundoPerfil.setBounds(0, 0, 750, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrescreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrescreverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrescreverActionPerformed

    private void jButtonRelatórioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatórioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRelatórioActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonPrescrever;
    private javax.swing.JButton jButtonRelatório;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApelido;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelDescri;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelFundoPag;
    private javax.swing.JLabel jLabelFundoPerfil;
    private javax.swing.JLabel jLabelGrupoSang;
    private javax.swing.JLabel jLabelMorada;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelNTel;
    private javax.swing.JLabel jLabelNacionalidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPatologia;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelSexo3;
    private javax.swing.JLabel jLabelUtente;
    private javax.swing.JPanel jPanelFundoPerfil;
    private javax.swing.JPanel jPanelPerfil;
    // End of variables declaration//GEN-END:variables
}
