/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.healthProfessional;

import backend.pojos.HealthProfessional;
import backend.ws.HealthProfessionalWS;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author jorge
 */
public class healthprofprof extends javax.swing.JFrame {

    private Logger log = Logger.getLogger(HealthProfessionalProfile.class);
    private HealthProfessionalWS hpWS;
    private HealthProfessional hp;

    public healthprofprof(int idHealthProfessional) {

        try {
            initComponents();
            hpWS = new HealthProfessionalWS();
            hp = hpWS.getHealthProfessionalById(idHealthProfessional);
           setFields(hp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(healthprofprof.this,
                    e.getMessage(), "Erro ao carregar os dados do Profissional de Saúde", JOptionPane.ERROR_MESSAGE);
        }
    }

    healthprofprof() {
    }

    private void setFields(HealthProfessional hp) {
        this.jTextFieldName.setText(hp.getName());
        this.jTextFieldGender.setText(hp.getLastName());
        this.jTextFieldBirthDate.setText(hp.getBirthDate());
        this.jTextFieldGender.setText(hp.getGender());
        this.jTextFieldMaritalStatus.setText(String.valueOf(hp.getNumTel()));
        this.jTextFieldBloodGroup.setText(hp.getNacionality());
        this.jTextFieldNacio.setText(hp.getAdress());
        this.jTextFieldAdress.setText(hp.getEmail());
        this.jTextFieldInstitution.setText(String.valueOf(hp.getNumCC()));
        this.jTextFieldNIF.setText(String.valueOf(hp.getNif()));
        this.jTextFieldMaritalStatus.setText(hp.getMaritalStatus());
        this.jTextFieldLastName.setText(hp.getBloodGroup());
        this.jTextFieldInstitution.setText(hp.getInstitution());

        if (hp.getPicture().equals("profile")) {
            ImageIcon pic = new ImageIcon(getClass().getResource("/imagens/fotos/perfil.PNG"));
            jLabelPhoto.setIcon(new ImageIcon(pic.getImage().getScaledInstance(
                    jLabelPhoto.getWidth(), jLabelPhoto.getHeight(), Image.SCALE_DEFAULT)));
        } else {
            jLabelPhoto.setIcon(new ImageIcon(getImageFromServer(hp.getPicture(), 90, 90)));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelwallpaper = new javax.swing.JLabel();
        jPanelWallpaper = new javax.swing.JPanel();
        jPanelInformation1 = new javax.swing.JPanel();
        jLabelHealthProfessionalProfile1 = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelBirthDate = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelNationality = new javax.swing.JLabel();
        jLabelAdress = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jLabelMaritalStatus = new javax.swing.JLabel();
        jLabelBloodType = new javax.swing.JLabel();
        jLabelInstitution = new javax.swing.JLabel();
        jTextFieldMaritalStatus = new javax.swing.JTextField();
        jTextFieldAdress = new javax.swing.JTextField();
        jTextFieldNacio = new javax.swing.JTextField();
        jTextFieldGender = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldBloodGroup = new javax.swing.JTextField();
        jTextFieldInstitution = new javax.swing.JTextField();
        jTextFieldNIF = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNCC = new javax.swing.JTextField();
        jTextFieldNTel = new javax.swing.JTextField();
        jTextFieldBirthDate = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jButtonBack1 = new javax.swing.JButton();
        jButtonEdit1 = new javax.swing.JButton();
        jLabelInformation = new javax.swing.JLabel();
        jLabelwallpaper1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabelwallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos/fundo2.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(705, 520));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelWallpaper.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanelWallpaper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInformation1.setMaximumSize(new java.awt.Dimension(680, 380));
        jPanelInformation1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHealthProfessionalProfile1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelHealthProfessionalProfile1.setText("Profissional de Saúde");
        jPanelInformation1.add(jLabelHealthProfessionalProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fotos/perfil.PNG"))); // NOI18N
        jPanelInformation1.add(jLabelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 80));

        jLabelName.setText("Nome:");
        jPanelInformation1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 55, -1, -1));

        jLabelBirthDate.setText("Data de nascimento:");
        jPanelInformation1.add(jLabelBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 85, -1, -1));

        jLabelTel.setText("Nº Tel:");
        jPanelInformation1.add(jLabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 115, -1, -1));

        jLabelCC.setText(" Nº CC:");
        jPanelInformation1.add(jLabelCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 175, -1, -1));

        jLabelEmail.setText("Email:");
        jPanelInformation1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 175, -1, -1));

        jLabelLastName.setText("Apelido:");
        jPanelInformation1.add(jLabelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 55, -1, -1));

        jLabelGender.setText("Sexo:");
        jPanelInformation1.add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 85, -1, -1));

        jLabelNationality.setText("Nacionalidade:");
        jPanelInformation1.add(jLabelNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 115, -1, -1));

        jLabelAdress.setText("Morada:");
        jPanelInformation1.add(jLabelAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 145, -1, -1));

        jLabelNIF.setText("  NIF:");
        jPanelInformation1.add(jLabelNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 205, 30, -1));

        jLabelMaritalStatus.setText(" Estado Civil:");
        jPanelInformation1.add(jLabelMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 205, -1, -1));

        jLabelBloodType.setText("  Grupo sanguíneo:");
        jPanelInformation1.add(jLabelBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 235, -1, -1));

        jLabelInstitution.setText(" Instituição:");
        jPanelInformation1.add(jLabelInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 235, -1, -1));

        jTextFieldMaritalStatus.setEditable(false);
        jTextFieldMaritalStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 150, -1));

        jTextFieldAdress.setEditable(false);
        jTextFieldAdress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 410, -1));

        jTextFieldNacio.setEditable(false);
        jTextFieldNacio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldNacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 150, -1));

        jTextFieldGender.setEditable(false);
        jTextFieldGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 150, -1));

        jTextFieldLastName.setEditable(false);
        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 150, -1));

        jTextFieldBloodGroup.setEditable(false);
        jTextFieldBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 150, -1));

        jTextFieldInstitution.setEditable(false);
        jTextFieldInstitution.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldInstitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, -1));

        jTextFieldNIF.setEditable(false);
        jTextFieldNIF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 150, -1));

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, -1));

        jTextFieldNCC.setEditable(false);
        jTextFieldNCC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 150, -1));

        jTextFieldNTel.setEditable(false);
        jTextFieldNTel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldNTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));

        jTextFieldBirthDate.setEditable(false);
        jTextFieldBirthDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelInformation1.add(jTextFieldBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 150, -1));

        jTextFieldName.setEditable(false);
        jTextFieldName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jPanelInformation1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 150, -1));

        jButtonBack1.setText("Voltar");
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });
        jPanelInformation1.add(jButtonBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jButtonEdit1.setText("Editar");
        jButtonEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdit1ActionPerformed(evt);
            }
        });
        jPanelInformation1.add(jButtonEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabelInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos/fundo_branco.jpg"))); // NOI18N
        jLabelInformation.setMaximumSize(new java.awt.Dimension(680, 380));
        jLabelInformation.setMinimumSize(new java.awt.Dimension(680, 380));
        jLabelInformation.setPreferredSize(new java.awt.Dimension(680, 380));
        jPanelInformation1.add(jLabelInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelWallpaper.add(jPanelInformation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 680, 380));

        jLabelwallpaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos/fundo2.jpg"))); // NOI18N
        jPanelWallpaper.add(jLabelwallpaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        new HealthProfessionalMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void jButtonEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdit1ActionPerformed
        new HealthProfessionalEdit(hp).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonEdit1ActionPerformed


    private Image getImageFromServer(String picture, int with, int heigth) {
        try {
            URL url = new URL("http://localhost/mu-pen-web/imagens/HealthProfessionals/" + picture.trim());
            log.debug("\n\tProfile Image: " + url.toString());
            BufferedImage image = ImageIO.read(url);
            ImageIcon pic = new ImageIcon(image);
            return pic.getImage().getScaledInstance(with, heigth, Image.SCALE_DEFAULT);
        } catch (MalformedURLException ex) {
            log.error(ex.getMessage());
            throw new RuntimeException("Erro ao carregar imagem");
        } catch (IOException ex) {
            log.error(ex.getMessage());
            throw new RuntimeException("Erro ao carregar imagem");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonEdit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdress;
    private javax.swing.JLabel jLabelBirthDate;
    private javax.swing.JLabel jLabelBloodType;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelHealthProfessionalProfile1;
    private javax.swing.JLabel jLabelInformation;
    private javax.swing.JLabel jLabelInstitution;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelMaritalStatus;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNationality;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelwallpaper;
    private javax.swing.JLabel jLabelwallpaper1;
    private javax.swing.JPanel jPanelInformation1;
    private javax.swing.JPanel jPanelWallpaper;
    private javax.swing.JTextField jTextFieldAdress;
    private javax.swing.JTextField jTextFieldBirthDate;
    private javax.swing.JTextField jTextFieldBloodGroup;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldInstitution;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMaritalStatus;
    private javax.swing.JTextField jTextFieldNCC;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldNTel;
    private javax.swing.JTextField jTextFieldNacio;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
